name: Activate and Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  BuildAndDeploy:
    name: Build and Deploy ✔
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Activate Unity
        uses: webbertakken/unity-activate@v1.2
        
      - name: free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
        
      - name: Build for Android
        uses: webbertakken/unity-builder@v0.11
        with:
          projectPath: ./
          unityVersion: 2018.4.14f1
          targetPlatform: Android

      - name: Deploy 
        uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
